### ISSUE TITLE
Advanced Hybrid Directory Demo: 03_HYBRIDDIR-NESTED-ONPREM-AD error

### ISSUE THREAD

**Issue by sapien47** [acantril/learn-cantrill-io-labs#39]
Hello,

I have tried several times to deploy the CloudFormation (CFN) Nested Stack.
I keep having an issue with the 03_HYBRIDDIR-NESTED-ONPREM-AD, when building the DomainController2 

DomainController2 | CREATE_FAILED | **Failed to receive 1 resource signal(s) within the specified duration**
HYBRIDDIR-ONPREMAD-FEU63JAX72I9 | CREATE_FAILED | **The following resource(s) failed to create: [DomainController2].**

Troubleshooting steps : I tried to deactivate the CFN Rollback Failure, The domain controller EC2 instance is built, I connected to it, there were no errors, but could not determine what was the issue, the cfn logs were created but empty.
```
  DomainController2:
    Type: AWS::EC2::Instance
    DependsOn: DomainController1
    CreationPolicy:
      ResourceSignal:
        Timeout: PT60M
        Count: 1
```
Any idea ? I really would like to perfrom this hands on labs.

Thank you for your attention
